### PR TITLE
Fix malformed JSON output and indent consistently

### PR DESCRIPTION
**Pull request by mmoya**
The module outpus a malformed json, for example:

```
{
"total": 1,
 "up": 0,
 "down": 1,
 "max": 6000,
"items": [
    {"name": "app1-10.10.10.11:80-10.10.10.11:80","addr": "10.10.10.11:80","access_time": 2023/05/12 09:52:02, "status": "down"},
  ]
}
```

- items' members are always suffixed with ','
- access_time value is not quoted

### CODE REVIEW

**Comment by alexzzh** [comment]
Hi mmoya!
I have invited you to maintain this module together, you can commit the code directly to this mode if requred.

**Comment by mmoya** [comment]
> Hi mmoya! I have invited you to maintain this module together, you can commit the code directly to this mode if required. I will also solve problems that may be encountered with this module in a timely manner.

Hi Alex.

Thank you for inviting me to the repo.

After testing this module in production (I don't have capacity to replicate production load outside production) I observed two problems:

- Our monitor raised alerts for several sites (response time dropping below acceptable).
- The amount of sustained connections was less than with stock nginx.

I didn't do a proper benchmark due to lack of bandwidth but from looking at some dashboard I'd say a drop in handled connections between 10%-20%.

After seeing that, I decided to try the [ngx_healthcheck_module](https://github.com/zhouchangxun/ngx_healthcheck_module) and it has been working as expected (expected as in 'switch stock nginx binary with nginx+module binary and nobody notices').

Our use case is (I guess) the most common out there:

- Having a few servers behind nginx (concretely n=2)
- Static configuration, no need to add/remove servers via API because of low n.

So I guess I will never see the problem you saw with the linked-list vs. rbtree.

If I found a problem with healthcheck module and provide a fix, I'll evaluate if the fix is something valuable for this repo and will submit a PR. It's unlikely, though, because maintaining a healthcheck module for nginx is not part of my core duties.

Regards

**Comment by alexzzh** [comment]
Hi, mmoya!

if you don't need to dynamically add or delete servers by APIs(by ngx_http_health_detect_upstream_add_peer/ngx_http_health_detect_upstream_delete_peer function or by restful api), you probably won't found most of the issues I've listed. But, if you need dynamiclly add or delete servers, eg: use this module with nginx-upstream-dynamic-resolve-servers module or tenegine dynamic module etc , this module is better choice, ngx_healthcheck_module not support yet.

I would like to confirm: 
"Our monitor raised alerts for several sites (response time dropping below acceptable).
The amount of sustained connections was less than with stock nginx. I didn't do a proper benchmark due to lack of bandwidth but from looking at some dashboard I'd say a drop in handled connections between 10%-20%."  ----   Wouldn't these two issues appear on module ngx_healthcheck_module?    

Finally, I want say that the biggest difference of two module is dynamic APIs, so  
both ngx_healthcheck_module and this module have same detect logic, will periodiclly detect server health status by nginx timers, it will create short/long connection and consume connection resources，the same issue may occur on both modules, please let me know or submiot PR. 

Thank you for your contribution!


Regards!

**Comment by alexzzh** [comment]
Hi mmoya!

Maybe my test method is inccorect, so I can not find this peroblem,  can you introduce your test method?  eg: nginx config,  the number of servers within one upstream,  TPS value,  the numbers of process? 

Can you be sure that this problem occurs with this module, but not with [ngx_healthcheck_module](https://github.com/zhouchangxun/ngx_healthcheck_module) module?    This is very strange for me.  so thanks! @mmoya

**Comment by mmoya** [comment]
Alex, the most important part of my previous message is "can't do a proper benchmark".

The metric I looked at was the amount of forwarded requests from cloudflare to nginx, thus I didnt looked at nginx metrics directly, just those from cloudflared.

So without a proper benchmark is hard to get to the cause.

I'll be difficult for me to benchmark this and stay within our SLO. I don't have a proper staging environment.

**Comment by alexzzh** [comment]
Hi mmoya,
so thanks for your reply.
I don't want you spend time to do benchmark test,  just wanted to confirm this problem "ONLY" occurs with this module, but not with ngx_healthcheck_module module?  beacuse I hadn't noticed this problem before and it has a relatively large impact on our project.  In your project, it may be easier to confirm that.
Thanks again.

**Comment by mmoya** [comment]
> ... just wanted to confirm this problem "ONLY" occurs with this module, but not with ngx_healthcheck_module module?

I can confirm that.

Adding more context:

nginx-health-detect-test

This graph is actually a metric from [cloudflared](https://github.com/cloudflare/cloudflared), which is a reverse proxy in front of nginx, running as a local process next to nginx in each of the machines.

In the first red line (few minutes before 16:00) the stock nginx is swapped with nginx+healthdetect in `lb2`. Just a systemd unit override for changing the binary.. While nginx+healthdetect was active, I had a console querying the status endpoint on a loop. Upstream servers were seen as UP all the time (as expected).

Between the first and the second red line two things happened:
1. `lb2` didn't recovered the nominal value of ~ 1K rps as before the change.
2. A third party monitor was sending alerts because it was getting 502 from several sites.

I gave up and rolled back to stock nginx (second line approximately).

I did the test with healthcheck_module the day after. After the `systemctl restart nginx` no performance drop took place and the performance monitor didn't raise any alert, like it nothing had changed. To the point that after a couple of hours, we proceeded to deploy nginx+healthcheck in lb1 as well.

**Pull request merged**
